project:
  type: website

website:
  title: "Ruty Korotaev"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 2023_Ruty_Korotaev_CV.pdf
        text: CV
      
format:
  html:
    theme: journal
    css: styles.css
    toc: true

